update react template

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -53,7 +53,11 @@ mv build/vue/v3.tgz dist/vue/v3.tgz
 
 # This is required to use 'npm link' when testing local builds
 # We do this last so unneed files are not included in the releases.
-log '👀 Install and Linting'
-concurrently --kill-others-on-fail "npm ci --loglevel=error --prefix=build/vue/v3" "npm ci --loglevel=error --prefix=build/vue/v2" "npm ci --loglevel=error --prefix=build/react" "npm i --prefix=build/onesignal-ngx"
+log '👀 Install + Linting + Build'
 
-log '✅ Done!'
+if concurrently --kill-others-on-fail "npm ci --loglevel=error --prefix=build/vue/v3" "npm ci --loglevel=error --prefix=build/vue/v2" "npm ci --loglevel=error --prefix=build/react" "npm i --prefix=build/onesignal-ngx"; then
+  log '✅ Done!'
+else
+  log '❌ Build failed!'
+  exit 1
+fi
